### ISSUE TITLE
Adding SCS to your Loadout after spawning correctly adds the implant, but leaves you at 50 energy.

### ISSUE THREAD

**Issue by Sweepi** [punyhumangames/Dystopia#24] opened 2018-02-17 15:12 UTC
If a player spawns while still editing his loadout, he does instantly respawn (as intended) once the edit is finished.
However if SCS was not in the loadout at the former spawn, the player only has 50/75 energy after the respawn.

**Comment by atomy** [comment] 2018-02-17 15:27
I know this bug/feature from back in the days, I just dont know if it was intended or also a bug in earlier versions...

**Comment by Joshua-Ashton** [comment] 2018-07-13 00:59
Fixed in next update.

**Closed by Joshua-Ashton** 2018-07-13 00:59 UTC
Labels: bug
